spring:
    application:
        name: order
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/SpringCloud_Sell?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: admin
    redis:
        host: 169.254.171.73
        port: 6379
        password: 123456            
server:
    port: 8082
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
        getProductList:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 3000
feign:
    hystrix:
        enabled: true
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1    
env:
    dev22222
    
