spring:
    application:
        name: user
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/SpringCloud_Sell?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    redis:
        host: 169.254.171.73
        port: 6379
        password: 123456            
server:
    port: 8085
env:
    dev22222
